### ISSUE TITLE
Stuck on Grabbing the GOX XML file

### ISSUE THREAD

**Issue by fuzzmz** [sjp/GOMstreamer.NET#1]
Running the latest version (0.10.0) it gets stuck and unresponsive at the Grabbing the GOX XML file stage.

**Comment by sjp** [comment]
Thanks for the bug report!

I've fixed the issue now. It should be working for you tomorrow (when I push out an update).

The two problems that caused this issue were firstly that I wasn't limiting the available streams early enough. Secondly, the code which drops quality to levels that you have access to (i.e. for free users that try HQ, will attempt SQ, then attempt SQTest.) did not have the correct logic and got stuck in a loop :(.

**Comment by fuzzmz** [comment]
No problem. Going to close this issue and wait for the patch.

**Comment by sjp** [comment]
Fixed in 98001968e4c3e83facd30435eba9d61a0fb12f0a
